export const MainEditorTheme = {
  ltr: "ltr",
  rtl: "rtl",
  paragraph: "editor-paragraph",
  quote: "editor-quote",
  heading: {
    h1: "editor-heading-h1",
    h2: "editor-heading-h2",
    h3: "editor-heading-h3",
    h4: "editor-heading-h4",
    h5: "editor-heading-h5",
    h6: "editor-heading-h6",
  },
  list: {
    listitem: "editor-list-item",
    ul: "editor-list-ul",
    listitemChecked: "editor-list-item-checked",
    listitemUnchecked: "editor-list-item-unchecked",
    nested: {
      listitem: "editor-nested-list-item",
    },
    olDepth: [
      "editor-list-ol-depth-1",
      "editor-list-ol-depth-2",
      "editor-list-ol-depth-3",
      "editor-list-ol-depth-4",
      "editor-list-ol-depth-5",
    ],
  },
  hashtag: "editor-hashtag",
  image: "editor-image",
  link: "editor-link",
  text: {
    bold: "editor-text-bold",
    code: "editor-text-code",
    italic: "editor-text-italic",
    strikethrough: "editor-text-strikethrough",
    subscript: "editor-text-subscript",
    superscript: "editor-text-superscript",
    underline: "editor-text-underline",
    underlineStrikethrough: "editor-text-underline-strikethrough",
  },
  code: "editor-code",
  codeHighlight: {
    atrule: "editor-code-token-attr",
    attr: "editor-code-token-attr",
    boolean: "editor-code-token-property",
    builtin: "editor-code-token-selector",
    cdata: "editor-code-token-comment",
    char: "editor-code-token-selector",
    class: "editor-code-token-function",
    "class-name": "editor-code-token-function",
    comment: "editor-code-token-comment",
    constant: "editor-code-token-property",
    deleted: "editor-code-token-property",
    doctype: "editor-token-comment",
    entity: "editor-code-token-operator",
    function: "editor-code-token-function",
    important: "editor-code-token-variable",
    inserted: "editor-code-token-selector",
    keyword: "editor-code-token-attr",
    namespace: "editor-code-token-variable",
    number: "editor-code-token-property",
    operator: "editor-code-token-property",
    prolog: "editor-code-token-comment",
    property: "editor-code-token-property",
    punctuation: "editor-code-token-punctuation",
    regex: "editor-code-token-variable",
    selector: "editor-code-token-selector",
    string: "editor-code-token-selector",
    symbol: "editor-code-token-property",
    tag: "editor-code-token-property",
    url: "editor-code-token-property",
    variable: "editor-code-token-selector",
  },
  embed: "editor-embed",
  table: "editor-table",
  tableAddColumns: "table-add-columns",
  tableAddRows: "table-add-rows",
  tableCell: "table-cell",
  tableCellActionButton: "table-cell-action-button",
  tableCellActionButtonContainer: "table-cell-action-button-container",
  tableCellEditing: "table-cell-editing",
  tableCellHeader: "table-cell-header",
  tableCellPrimarySelected: "table-cell-primary-selected",
  tableCellResizer: "table-cell-resizer",
  tableCellSelected: "table-cell-selected",
  tableCellSortedIndicator: "table-cell-sorted-indicator",
  tableResizeRuler: "table-cell-resize-ruler",
  tableSelected: "table-selected",
  tableSelection: "table-selection",
};
